### ISSUE TITLE
AttributeError: 'BaxH5Reader' object has no attribute '_ccsBasecallsGroup'

### ISSUE THREAD

**Issue by basiek** [PacificBiosciences/pbbarcode#2]
I am trying to run pbbarcode labelZmws and I am using barcode fasta file and list of bas.h5 as an input (input.fofn) and I get following error:
<pre>
 AttributeError: 'BaxH5Reader' object has no attribute '_ccsBasecallsGroup'
</pre>
Is pbbarcode labelZmws expecting input.fofn to contain list of bax.h5 files? 

Many thanks,
B.

**Comment by mjhsieh** [comment]
Hi, if you are still interested, can you post more Traceback information? My suspicion is that you are mixing base hdf5 files from different generations of the software. An ```ls -l``` to the h5 files would be nice.

**Comment by gawbul** [comment]
Same issue here:

```
[smoss@biolserva reads]$ bash5tools.py --outType fastq LIMS4462.h5 
Traceback (most recent call last):
  File "/biol/people/smoss/.pyenv/versions/2.7.10/bin/bash5tools.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbh5tools==0.8.0', 'bash5tools.py')
  File "/biol/people/smoss/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/biol/people/smoss/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/bash5tools.py", line 166, in <module>
    sys.exit(BasH5ToolsRunner().start())
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbcore-1.0.0-py2.7.egg/pbcore/util/ToolRunner.py", line 109, in start
    return self.run()
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/bash5tools.py", line 121, in run
    inBasH5 = BasH5Reader(self.args.inFile)
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbcore-1.0.0-py2.7.egg/pbcore/io/BasH5IO.py", line 809, in __init__
    self._parts = [ BaxH5Reader(self.filename) ]
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbcore-1.0.0-py2.7.egg/pbcore/io/BasH5IO.py", line 473, in __init__
    else self._ccsBasecallsGroup
AttributeError: 'BaxH5Reader' object has no attribute '_ccsBasecallsGroup'
```

```
[smoss@biolserva reads]$ ls -lh
total 674M
-rw-r--r-- 1 smoss biol 674M Jan 11 20:36 LIMS4462.h5
```

**Comment by gawbul** [comment]
I did the following:

```
[smoss@biolserva downloads]$ git clone https://github.com/PacificBiosciences/pbcore.git && cd pbcore
Cloning into 'pbcore'...
remote: Counting objects: 2758, done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 2758 (delta 54), reused 0 (delta 0), pack-reused 2691
Receiving objects: 100% (2758/2758), 15.41 MiB | 3.53 MiB/s, done.
Resolving deltas: 100% (1839/1839), done.
Checking connectivity... done.

[smoss@biolserva pbcore]$ git tag -l
0.6.0
0.7.0
0.8.0
0.9.1
0.9.3
1.0.0
2.3-bam
smrtanalysis-2.1
smrtanalysis-2.2
smrtanalysis-2.3.0p1

[smoss@biolserva pbcore]$ git checkout tags/0.8.0                                                                                                                                                             
Note: checking out 'tags/0.8.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at edeffb4...    Bug 23893. Add a bam file with quiver QVs as optional tags.
```

Followed by `pip uninstall pbcore && python setup.py install`. Now I get the following:

```
[smoss@biolserva reads]$ bash5tools.py --outType fastq LIMS4462.h5 
Traceback (most recent call last):
  File "/biol/people/smoss/.pyenv/versions/2.7.10/bin/bash5tools.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbh5tools==0.8.0', 'bash5tools.py')
  File "/biol/people/smoss/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/biol/people/smoss/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/bash5tools.py", line 166, in <module>
    sys.exit(BasH5ToolsRunner().start())
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbcore-0.8.0-py2.7.egg/pbcore/util/ToolRunner.py", line 105, in start
    return self.run()
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbh5tools-0.8.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/bash5tools.py", line 121, in run
    inBasH5 = BasH5Reader(self.args.inFile)
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbcore-0.8.0-py2.7.egg/pbcore/io/BasH5IO.py", line 582, in __init__
    self._parts = [ BaxH5Reader(self.filename) ]
  File "/biol/people/smoss/.pyenv/versions/2.7.10/lib/python2.7/site-packages/pbcore-0.8.0-py2.7.egg/pbcore/io/BasH5IO.py", line 336, in __init__
    if "BaseCalls" in self.file["/PulseData"]:
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-KYQHrY/h5py/h5py/_objects.c:2453)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-KYQHrY/h5py/h5py/_objects.c:2410)
  File "/biol/people/smoss/.local/lib/python2.7/site-packages/h5py/_hl/group.py", line 164, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-KYQHrY/h5py/h5py/_objects.c:2453)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-KYQHrY/h5py/h5py/_objects.c:2410)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip-build-KYQHrY/h5py/h5py/h5o.c:3363)
KeyError: "Unable to open object (Object 'pulsedata' doesn't exist)"
```

**Comment by gawbul** [comment]
Tried older (version 1.3.0) of `h5py` along with `pbcore` 0.8.0 too, but wouldn't install as incompatible with latest `distutils`.

**Comment by gawbul** [comment]
From what I can tell, I have the original single-part `bas.h5` from the PacBio RS system. Are there any tools available to work with those data still? The current tools only seem to support the newer multi-part `bas.h5` and `bax.h5` format?

**Comment by gawbul** [comment]
Is there possible something wrong with the file, or perhaps it is indeed the more recent format, and I simply haven't been supplied with the `bax.h5` files?

`h5ls` gives me the following:

```
$ h5ls LIMS4462.h5
Diagnostics              Group
EventsData               Group
FL                       Group
FrameJobLog              Group
MovieCal                 Group
Settings                 Group
TI                       Group
TraceJobLog              Group
```

**Comment by gawbul** [comment]
Tried with `R-pbh5` as well. Get the following:

```
> library(pbh5)
Loading required package: h5r
> pb_data <- PacBioBasH5('LIMS4462.h5')
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: H5G.c line 467 in H5Gopen2(): unable to open group
    major: Symbol table
    minor: Can't open object
  #001: H5Gint.c line 320 in H5G__open_name(): group not found
    major: Symbol table
    minor: Object not found
  #002: H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
Error in .local(h5Obj, groupName, ...) : 
  Group: PulseData/BaseCalls cannot be opened.
Calls: PacBioBasH5 ... .initBasEvents -> getH5Group -> getH5Group -> .local
Execution halted
```

Got a feeling perhaps this is an PB RS II dataset, and I'm missing the `bax.h5` files?

**Comment by dalexander** [comment]
we never use bas files in FOFNs, so that is most certainly the problem.  Use bax.h5 files only.

**Comment by gawbul** [comment]
Yes, that was the problem! The bax.h5 files weren't supplied. Have retrieved them now. Many thank, @dalexander :smile:
